name: "Reusable Build & Distribute"

on:
  workflow_call:
    inputs:
      flavor:
        required: true
        type: string
    secrets:
      GCP_SA_KEY:
        required: true
      FIREBASE_APP_ID:
        required: true
      PROJECT_ID:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Get Latest Build Number
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=service-account.json
          
          # Fetch the latest build version from Firebase
          # We use jq to parse the JSON output and get the buildVersion of the first item
          LATEST_BUILD=$(firebase appdistribution:releases:list --app "${{ secrets.FIREBASE_APP_ID }}" --project "${{ secrets.PROJECT_ID }}" --limit 1 --json | jq '.[0].buildVersion' -r)
          
          echo '$LATEST_BUILD'
          
          if [ "$LATEST_BUILD" == "null" ] || [ -z "$LATEST_BUILD" ]; then
            echo "NEW_BUILD_NUMBER=1" >> $GITHUB_ENV
          else
            echo "NEW_BUILD_NUMBER=$((LATEST_BUILD + 1))" >> $GITHUB_ENV
          fi

      - name: Build APK
        run: |
          flutter build apk \
            --target lib/main-${{ inputs.flavor }}.dart \
            --debug \
            --build-number=${{ env.NEW_BUILD_NUMBER }}

      - name: Upload to Firebase
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=service-account.json
          
          # Use wildcards or the specific flavor name for the APK path
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-debug.apk \
            --app "${{ secrets.FIREBASE_APP_ID }}" \
            --project "${{ secrets.PROJECT_ID }}" \
            --groups "qa" \
            --release-notes "Automated Build #${{ env.NEW_BUILD_NUMBER }} from GitHub Actions"